In [1]:
import tensorflow as tf

C:\Users\Sara\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Sara\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Sara\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Sara\anaconda3\envs\tf\lib\site-packages\tensorflow\python\framework\dtypes.

In [2]:
tf.__version__

'1.10.0'

In [5]:
hello=tf.constant("Hello")
hello

<tf.Tensor 'Const_1:0' shape=() dtype=string>

In [6]:
world=tf.constant("World")
world

<tf.Tensor 'Const_2:0' shape=() dtype=string>

In [7]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [9]:
with tf.Session() as sess:
    result=sess.run(hello+world)
print(result)

b'HelloWorld'


In [10]:
var1=tf.constant(10)
var2=tf.constant(20)
var1+var2

<tf.Tensor 'add_2:0' shape=() dtype=int32>

In [11]:
with tf.Session() as sess:
    result=sess.run(var1+var2)
print(result)

30


In [15]:
constant=tf.constant(10)
matrix=tf.fill((5,5),10)
zeros=tf.zeros((5,5))
ones=tf.ones((5,5))
randn=tf.random_normal((4,4),mean=0,stddev=1)
randu=tf.random_uniform((4,4),minval=0,maxval=1)

In [16]:
myops=[constant,matrix,zeros,ones,randn,randu]

In [17]:
sess=tf.InteractiveSession()

C:\Users\Sara\anaconda3\envs\tf\lib\site-packages\tensorflow\python\client\session.py:1645: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [18]:
for op in myops:
    print(sess.run(op))
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


[[-0.01450397  0.6589324   0.0709809  -1.8581262 ]
 [-2.125311   -0.33495018  0.91727835 -0.69546634]
 [-0.85972947 -0.07771969  0.8727924   1.0137265 ]
 [ 0.59366447 -0.79855573  0.32406184  0.16152678]]


[[0.28221524 0.73112106 0.16365504 0.02603829]
 [0.33122933 0.6392609  0.7254602  0.9016057 ]
 [0.68003464 0.07232153 0.71389997 0.87702465]
 [0.2697928  0.8155476  0.22483063 0.3316332 ]]




In [20]:
a=tf.constant([[1,2],[3,4]])
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [21]:
b=tf.constant([[10],[100]])
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [23]:
result=tf.matmul(a,b)

In [24]:
sess.run(result)

array([[210],
       [430]])